<?php
/** @var \ScandicDesi\SizeChart\Block\Chart $block */

/** @var \ScandicDesi\SizeChart\Model\Chart $chart */
$chart = $block->getSizeChart();
?>
<p><a href="#size-chart" data-role="sizechart"><?php echo __('Size Chart'); ?></a></p>
<div class="size-chart no-display" data-mage-init='{"sizeChart":{"actionSelector": "[data-role=sizechart]"}}'>
    <h2 class="size-chart-title">
        <?php echo $chart->getTitle(); ?>
    </h2>
    <div class="size-chart-content">
        <?php echo $block->filterContent($chart->getContent()); ?>
    </div>
</div>
