<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Website switcher template
 *
 * @see \Echidna\Custom\Block\HomeCategoriesList
 */

	$items = $block->getStoreCategories();
	$title = __('Shop By Occasion');
	$mode = "grid";
?>
<?php if ($items): ?>
<div class="block widget shop-by-occasion" >
    <div class="block-title">
        <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content">
        <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
            <ol class="owl-carousel  product-items shop-by-occasion-items"  data-mage-init='{
               "OwlCarousel":{
               
                "stagePadding": 200,
                "loop":true,
                "nav":true,
                "items":1,
                "lazyLoad": true,
                "nav":true,
                "responsive":{
                    "0":{
                        "items":1,
                        "stagePadding": 100
                    },
                    "600":{
                        "items":1,
                        "stagePadding": 100
                    },
                    "1000":{
                        "items":1,
                        "stagePadding": 100
                    },
                    "1200":{
                        "items":1,
                        "stagePadding": 100
                    },
                    "1400":{
                        "items":1,
                        "stagePadding": 100
                    },
                    "1600":{
                        "items":1,
                        "stagePadding": 100
                    },
                    "1800":{
                        "items":1,
                        "stagePadding": 100
                    }
                }
                
               
               
                }
            }'  > 
                <?php $iterator = 1; ?>

                <?php 	foreach ($items as $category) :  ?> 
                <?php  	$getCategoryObj = $block->getCategory($category);  
                $getImageUrl = $getCategoryObj->getImageUrl();?>

                <?php if ($category->getIsActive() && $getImageUrl ): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>

                <a href="<?php /* @escapeNotVerified */ echo $getCategoryObj->getUrl() ?>">

                <img src="<?php echo $getImageUrl; ?>">
                <p><?php echo $block->escapeHtml($category->getName()) ?></p>
                </a>


                <?php echo($iterator == count($items)+1) ? '</li>' : ''; ?>
                <?php endif; ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif; ?>

