<div class="block block-cart-offer" data-bind="scope: 'cartOffers'" data-role="cart-offers">
    <!-- Content -->
    <!-- ko if: cartOffers().shipping && getSubtotalBalance() -->
    <div class="message-area message" data-bind="css: {'success': cartOffers().shipping.title }">
        <strong data-bind="html: cartOffers().shipping.title" class="cart-offer-shipping-title"></strong>
        <span data-bind="html: getCartMessage()" class="cart-offer-shipping-message"></span>
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {"[data-role=cart-offers]": {"Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>}}
</script>