<?php
/**
 * Copyright © 2013-2017 ScandicDesi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \ScandicDesi\Megamenu\Block\Topmenu
 */
 

$parentCategory = $block->getParentCategory();
$categoryList = $block->getCategoryList();
?>
<ul>
    <?php if(count($parentCategory)): ?>
    <li>
        <h4>
            <a href="<?php echo $parentCategory->getUrl() ?>">
            <span><?php echo $parentCategory->getName() ?></span>
        </a>
        </h4>
    </li>
    <?php endif; ?>
    
    <?php foreach ($categoryList as $category): ?>
        <li>
            <a href="<?php echo $category->getUrl() ?>">
                <span><?php echo $category->getName() ?></span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>