<?php
/**
 * Copyright © 2013-2017 ScandicDesi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \ScandicDesi\Megamenu\Block\Topmenu
 */
 

$parentCategory = $block->getParentCategory();
$categoryList = $block->getCategoryList();
?>
<ul>
    <?php if(count($parentCategory)): ?>
    <li class="level1 parent custom-menu-level">
        <h4>
            <a href="<?php echo $parentCategory->getUrl() ?>">
            <span><?php echo $parentCategory->getName() ?></span>
        </a>
        </h4>
        
        <ul>
            <?php foreach ($categoryList as $category): ?>
                <li>
                    <a href="<?php echo $category->getUrl() ?>">
                        <span><?php echo $category->getName() ?></span>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    <?php endif; ?>
</ul>