<?php
/**
 * Copyright © 2013-2017 ScandicDesi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \ScandicDesi\Megamenu\Block\Topmenu
 */
?>
<ul>
    <li>
    <?php
        $category = $block->getCategory();
        $categoryField = $block->getContentField();
        echo $category->getData('megamenu_col_content' . $categoryField);
    ?>
    </li>
</ul>
