<div class="checkout-footer-content">
    <div class="payment_methods">
        <img src='<?php echo $this->getViewFileUrl('Magento_Checkout::images/checkout_payment_methods.png'); ?>' alt="checkout_payment_methods">
    </div>
    <div class="secure-checkout">
        <span>
        
             <img src='<?php echo $this->getViewFileUrl('Magento_Checkout::images/secure-checkout.svg'); ?>' alt="secure-checkout">
            <?php echo __('Secure Checkout'); ?>
        </span>
    </div>
</div>