<?php
/** @var \Algolia\AlgoliaSearch\Block\Algolia $block */

$config = $block->getConfigHelper();

$catalogSearchHelper = $block->getCatalogSearchHelper();

$placeholder = __('Search Here !');

/** Render form with autocomplete input **/
if ($config->isDefaultSelector()): ?>
<div class="mbl_search_btn"></div>
<div class="block block-search">
    <div class="block block-title"><strong><?php echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch"  id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
            <div id="algolia-searchbox">
				<div class="field search">
					<label class="label" for="search" data-role="minisearch-label"><?php echo __('Search:') ?></label>
					<div class="control" >
						<input 
							id="search" 
							type="text" 
							name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" 
							value="<?php /* @escapeNotVerified */ echo $catalogSearchHelper->getEscapedQueryText() ?>"
							maxlength="<?php /* @escapeNotVerified */ echo $catalogSearchHelper->getMaxQueryLength();?>"
							class="input-text algolia-search-input" 
							autocomplete="off" 
							spellcheck="false" 
							autocorrect="off" 
							autocapitalize="off" 
							placeholder="<?php echo $placeholder; ?>" 
						 />
						
					</div>
					<!-- <span class="clear-cross clear-query-autocomplete"></span> -->  
				</div>
				<div class="actions">
					<button type="submit"
							title="<?php echo $block->escapeHtml(__('Search')) ?>"
							class="action search input-field-button">
						<span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
						<span id="algolia-glass" class="magnifying-glass" width="24" height="24"></span>
					</button>
				</div>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>