<?php

namespace ScandicDesi\NewsletterPopup\Block;

use Magento\Cms\Block\Block as CmsBlock;
use Magento\Cms\Block\BlockFactory as CmsBlockFactory;
use Magento\Cms\Model\BlockRepository as CmsBlockRepo;
use Magento\Framework\View\Element\BlockFactory;
use Magento\Framework\View\Element\Template;
use Magento\Newsletter\Block\Subscribe as NewsletterSubscribe;
use ScandicDesi\NewsletterPopup\Model\Config;

/**
 * Created by PhpStorm.
 * User: vkranjith
 * Date: 03/09/17
 * Time: 9:36 AM
 */
class Subscribe extends Template
{
    const TEMPLATE = 'ScandicDesi_NewsletterPopup::subscribe_popup.phtml';

    /** @var Config */
    private $config;

    /** @var CmsBlockFactory */
    private $cmsBlockFactory;

    /** @var BlockFactory */
    private $blockFactory;

    /**
     * Subscribe constructor.
     * @param Template\Context $context
     * @param BlockFactory $blockFactory
     * @param CmsBlockFactory $cmsBlockFactory
     * @param Config $config
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        BlockFactory $blockFactory,
        CmsBlockFactory $cmsBlockFactory,
        Config $config,
        array $data = []
    ) {
        $this->blockFactory = $blockFactory;
        $this->cmsBlockFactory = $cmsBlockFactory;
        $this->config = $config;
        parent::__construct($context, $data);
    }

    /**
     * Get the Left Banner Block content
     *
     * @param $identifier
     * @return string
     */
    public function getLeftBlock($identifier)
    {
        try {
            /** @var CmsBlock $leftBlock */
            $leftBlock = $this->cmsBlockFactory->create();
            $leftBlock->setBlockId($identifier);
            $html = $leftBlock->toHtml();
        } catch (\Exception $e) {
            $html = '';
        }
        return $html;
    }

    public function getNewsletterBlock()
    {
        /** @var Template $newsletterBlock */
        $newsletterBlock = $this->blockFactory->createBlock(NewsletterSubscribe::class);
        $newsletterBlock->setTemplate('Magento_Newsletter::subscribe.phtml')->setTerminatePlugin(true);
        return $newsletterBlock->toHtml();
    }

    /**
     * @return string
     */
    protected function _toHtml()
    {
        if ($this->getTemplate() == null && $this->config->isEnabled()) {
            $this->setTemplate(self::TEMPLATE);
        }
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}